# data
augmentations: 'vit_heavy'
image_size: [384, 384]  # [height, width]
dataset: 'DF24'

# model
architecture: 'vit_base_patch16_384'

# training
train:
loss: 'SeeSawLoss'
optimizer: 'SGD'
scheduler: 'plateau'
epochs: 50
learning_rate: 0.01
batch_size: 32
accumulation_steps: 8

# other
random_seed: 777
workers: 12
multigpu: False
tags: ["DanishFungi2024", "384x384"]  # W&B Run tags
root_path: "../"