# data
augmentations: 'vit_heavy'
image_size: [384, 384]  # [height, width]
dataset: 'DF24M'

# model
architecture: 'tf_efficientnet_b3.ap_in1k'

# training
train:
loss: 'SeeSawLoss'
optimizer: 'SGD'
scheduler: 'plateau'
epochs: 50
learning_rate: 0.1
batch_size: 32
accumulation_steps: 8

# other
random_seed: 777
workers: 8
multigpu: False
tags: ["DanishFungi2024", "384x384", "Convolutional"]  # W&B Run tags
root_path: "../"