# data
augmentations: 'vit_heavy'
image_size: [384, 384]  # [height, width]
dataset: 'DF24'

# model
architecture: 'vit_base_patch16_384.augreg_in21k_ft_in1k'

# training
train:
loss: 'SeeSawLoss'
optimizer: 'SGD'
scheduler: 'plateau'
epochs: 50
learning_rate: 0.01
batch_size: 16
accumulation_steps: 16

# other
random_seed: 777
workers: 8
multigpu: False
tags: ["DF24-CloseSet", "384x384", "Convolutional"]  # W&B Run tags
root_path: "../"