# data
augmentations: 'vit_heavy'
image_size: [224, 224]  # [height, width]
dataset: 'DF24'

# model
architecture: 'vit_base_patch16_224'

# training
train:
loss: 'SeeSawLoss'
optimizer: 'SGD'
scheduler: 'plateau'
epochs: 50
learning_rate: 0.1
batch_size: 32
accumulation_steps: 8

# other
random_seed: 777
workers: 12
multigpu: False
tags: ["DanishFungi2024", "224x224"]  # W&B Run tags
root_path: "../"